# app_lucky_number:
#    path: /
#    controller: App\Controller\LuckyController::number

admin_api:
  type: rest
  resource: App\Controller\AdminApiController
  prefix: api/admin

product_admin_api:
  type: rest
  resource: App\Controller\ApiAdminProductController
  prefix: api/admin

test_api:
  type: rest
  resource: App\Controller\ApiAdminTestController
  prefix: api/admin/test

email_api:
  type: rest
  resource: App\Controller\MailController
  prefix: api/email/

# user_api:
#   type: rest
#   resource: App\Controller\UserApiController
#   prefix: api/user

user_:
  resource: App\Controller\UserController
  prefix: user

apporder_:
  resource: App\Controller\ShippingController
  prefix: shipping

testing_:
  resource: App\Controller\TestController
  prefix: testing